
development:
  adapter: postgresql
  encoding: unicode
  database: idea_share
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: idea_share
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: idea_share
  pool: 5

